name: ladder
adopt-info: ladder
base: core22
license: GPL-3.0
contact: https://github.com/popey/ladder-snap/issues
issues: https://github.com/popey/ladder-snap/issues
source-code: https://github.com/popey/ladder-snap
website: https://github.com/everywall/ladder
summary: Ladder is a web proxy to help bypass paywalls
description: |
  Selfhosted alternative to 12ft.io. and 1ft.io bypass paywalls with
  a proxy ladder and remove CORS headers from any URL

  This snap runs on port 8080, so once installed, point your browser at 
  https://localhost:8080 - or whatever host it's running on.
  
  This snap is maintained by Alan Pope, and is not
  necessarily endorsed or officially maintained by the upstream developers.

platforms:
  amd64:
  arm64:

grade: stable
confinement: strict

parts:
  ladder:
    plugin: make
    source: https://github.com/everywall/ladder
    source-type: git
    build-environment:
      - PATH: "$PATH:/root/go/bin"
    override-pull: |
      craftctl default
      # Checkout the latest tag
      last_committed_tag="$(git describe --tags --abbrev=0)"
      git checkout "${last_committed_tag}"
      VERSION="$(git describe --tags | sed 's/^v//')"
      craftctl set-version "${VERSION}"
      echo "${last_committed_tag#v}" > handlers/VERSION
    build-snaps:
      - go/latest/stable
      - goreleaser/latest/stable
    override-build: |
      goreleaser build --single-target
      install dist/ladder_linux_${SNAP_ARCH}*/ladder $SNAPCRAFT_PART_INSTALL

apps:
  ladder:
    command: ladder
    daemon: simple
    plugs:
      - network
      - network-bind
