name: ladder
title: Ladder
base: core24
version: '0.0.22'
license: GPL-3.0
contact: https://github.com/popey/ladder-snap/issues
issues: https://github.com/popey/ladder-snap/issues
source-code: https://github.com/popey/ladder-snap
website: https://github.com/everywall/ladder
summary: Ladder is a web proxy to help bypass paywalls
description: |
  Selfhosted alternative to 12ft.io. and 1ft.io bypass paywalls with
  a proxy ladder and remove CORS headers from any URL

  This snap runs on port 8080 by default. You can change the port with:

    snap set ladder port=9090

  To require Basic Auth (username:password), set:

    snap set ladder userpass=myuser:mypassword

  Then restart the service:

    snap restart ladder

  Point your browser at http://localhost:<port> once running.

  This snap is maintained by Alan Pope, and is not
  necessarily endorsed or officially maintained by the upstream developers.

platforms:
  amd64:
  arm64:

grade: stable
confinement: strict

parts:
  launcher:
    plugin: dump
    source: snap/local
    organize:
      ladder-launch: bin/ladder-launch

  ladder:
    plugin: make
    source: https://github.com/everywall/ladder
    source-type: git
    source-tag: 'v$SNAPCRAFT_PROJECT_VERSION'
    build-environment:
      - PATH: "$PATH:/root/go/bin"
    override-build: |
      echo "$SNAPCRAFT_PROJECT_VERSION" > handlers/VERSION
      goreleaser build --single-target
      install dist/ladder_linux_${SNAP_ARCH}*/ladder $SNAPCRAFT_PART_INSTALL
    build-snaps:
      - go/latest/stable
      - goreleaser/latest/stable

apps:
  ladder:
    command: bin/ladder-launch
    daemon: simple
    plugs:
      - network
      - network-bind
